### ISSUE TITLE
Possibility to receive the SelectedShapeIdChanged event when the readonly property is true

### ISSUE THREAD

**Issue by emiliosanchis** [florian03-1/BlazorSvgEditor#11]
Possibility to receive the SelectedShapeIdChanged event when the readonly property is true.

Or have an event that indicates that a shape has been clicked regardless of the value of the ReadOnly property

This is useful for once the shapes have been defined in an editor, to show a viewer to the user so that they can select one of the shapes.

Modifying the SelectAsync method of the ShapeEditor class as follows also raises the event when the property ReadOnly=true

     protected async Task SelectAsync(PointerEventArgs eventArgs)
     {
         if(eventArgs.PointerType == "touch") return; //Touch events are handled separately

         if (SvgElement.SvgEditor.EditMode == EditMode.Add) return;
         if (SvgElement.SvgEditor.ReadOnly)
         {
             await SvgElement.SvgEditor.SelectedShapeIdChanged.InvokeAsync(SvgElement.CustomId);
             return;
         }
        
         SvgElement.SelectShape();
         SvgElement.SvgEditor.SelectShape(SvgElement, eventArgs);
     }

**Comment by florian03-1** [comment]
Yes, this sounds like a good idea!

You can create an pull-request and I will merge it.
