### ISSUE TITLE
Add feature to duplicate shape

### ISSUE THREAD

**Issue by thomas-illiet** [florian03-1/BlazorSvgEditor#4]
I write following line do add this feature.

> SvgEditor.PublicMethods.cs

```csharp
public async Task DuplicateSelectedShape()
    {
        if (SelectedShape != null)
        {
            int deletedShapeId = SelectedShape.CustomId;
            Shape ? shape = Shapes.FirstOrDefault(s => s.CustomId == deletedShapeId);

            if (shape != null)
            {
                var newShape = shape.Clone();
                if (Shapes.Count > 0) newShape.CustomId = Math.Min(Enumerable.Min<Shape>(Shapes, x => x.CustomId) - 1, newShape.CustomId);

                Shapes.Add(newShape);
                await OnShapeChanged.InvokeAsync(ShapeChangedEventArgs.ShapeAdded(newShape));
            }
        }
        else
        {
            if (ShowDiagnosticInformation) Console.WriteLine("No shape selected - so nothing to duplicate");
        }
    }
```

> preview.razor

```html
<div class="inline-flex mt-2" role="group">
  <button @onclick="DuplicateShape" type="button" class="shadow-sm flex-grow focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2 mr-2">Duplicate Shape</button>
  <button @onclick="DeleteShape" type="button" class="shadow-sm flex-grow focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2">Delete Shape</button>
</div>
```

> preview.razor.cs

```csharp
private void DuplicateShape()
{
    svgEditor?.DuplicateSelectedShape();
}
```

> shape.cs

```csharp
public Shape Clone()
{
    Shape temp = (Shape)this.MemberwiseClone();
    return temp;
}
```

**Why use `int` for shape identification, when `Guid` is simpler?**

**Comment by florian03-1** [comment]
The reason for this is that in the project for which I programmed the editor, I had to know exactly whether a new form was created or already existed.

And I implemented that by always assigning the ID -1 to new forms - as soon as they are saved, they are automatically assigned a new number by the database anyway.


If you have an idea how to add a GUID, feel free to make a pull request

**Comment by thomas-illiet** [comment]
With guid, you don't need to know if a guid already exists,
because the probability of having the same guide is very very low.

> While each generated GUID is not guaranteed to be unique, the total number of unique keys (2128 or 3.4×1038) is so large that the probability of the same number being generated twice is very small. For example, consider the observable universe, which contains about 5×1022 stars; every star could then have 6.8×1015 universally unique GUIDs.
