### ISSUE TITLE
Image not centred after rendered

### ISSUE THREAD

**Issue by patupaka** [florian03-1/BlazorSvgEditor#9]
As you can see in the demo site, the image is not automatically centred in first render. With "centred" I mean is just like what "Reset Transformation" button does.
I tried to use the method ResetTransform() in OnAfterRenderAsync, after the ReloadImage(), and it does not do the same transformation as if i click the "Reset Transformation" button.

**Comment by florian03-1** [comment]
I cannot reproduce it - in my application it works like a charme...
Can you show me your code and I can take a look...?
